### ISSUE TITLE
Unhandled exception processing C:\Program Files\Cryptomator\app\mods\javafx-graphics-17.0.1-win.jar

### ISSUE THREAD

**Issue by rudolfb** [dbzoo/log4j_scanner#1]
Windows 11
python -m pip install pywin32
Python 3.10.1

Thanks, first, for offering this script.

Get the following error when running your script.

```
c:\dev\github\log4j_scanner>python scanner_win.py
Indicator for vulnerable component found in C:\$RECYCLE.BIN\S-1-5-21-67875770-1077041941-3688728843-1001\$RTYFQH1.jar: log4j 2.9.1-2.10.0
Unhandled exception processing C:\Program Files\Cryptomator\app\mods\javafx-graphics-17.0.1-win.jar
Traceback (most recent call last):
  File "c:\dev\github\log4j_scanner\scanner_win.py", line 88, in main
    if handleJar(filename, filename):
  File "c:\dev\github\log4j_scanner\scanner_win.py", line 72, in handleJar
    return handleJar(io.BytesIO(z.read(name)), filename.decode('utf-8')+":"+name)
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\dev\github\log4j_scanner\scanner_win.py", line 96, in <module>
    sys.exit(main())
  File "c:\dev\github\log4j_scanner\scanner_win.py", line 92, in main
    traceback.print_exc()
NameError: name 'traceback' is not defined
```

[https://agentonline-my.sharepoint.com/:u:/g/personal/rb_agentonline_ch/EbfK8iKhOhJGlnN-kqY4lPgB44x-VaSlmrhNDO7efo6Dbg?e=qtwzNh
](javafx-graphics-17.0.1-win.jar)

Any idea why this is causing an issue.

**Comment by dbzoo** [comment]
When I scan my Linux system with a file containing Unicode it works.   I'm using python 2.7 old I know, but it's what we have to use.  Your filename does not contain Unicode chars.  I've not had a problem with windows.  Let me check py3.

I do see however I forgot to "import traceback" in the windows scanner, triggering yet another exception. I'll fix that.

Reproduced that problem and fixed it.

**Comment by dbzoo** [comment]
Create a file called băd.ear the scan failed with the Unicode problem.  Thank you.  It's fixed.
